import io
from docx import Document

from app.services.resume_exporter import generate_resume_docx

# Mock payload mimicking what the frontend will send back
MOCK_OPTIMIZED_RESUME = {
    "summary": "Experienced software engineer with a focus on backend development.",
    "experience": [
        {
            "company": "Tech Corp",
            "role": "Backend Developer",
            "dates": "2021 - 2023",
            "bullets": [
                "Developed REST APIs using Python.",
                "Improved database performance by 20%."
            ]
        }
    ],
    "skills": [
        {
            "category": "Languages",
            "skills": ["Python", "SQL"]
        }
    ],
    "education": [
        {
            "institution": "University of Technology",
            "degree": "B.Sc. Computer Science",
            "dates": "2017 - 2021"
        }
    ]
}


def test_generate_resume_docx_creates_file():
    """Tests that the generator returns valid bytes."""
    docx_bytes = generate_resume_docx(MOCK_OPTIMIZED_RESUME)
    
    assert isinstance(docx_bytes, bytes)
    assert len(docx_bytes) > 0  # File should not be empty


def test_generate_resume_docx_contains_content():
    """Tests that the generated docx actually contains the text we passed in."""
    docx_bytes = generate_resume_docx(MOCK_OPTIMIZED_RESUME)
    
    # Open the generated bytes as a Document to inspect it
    doc = Document(io.BytesIO(docx_bytes))
    
    # Extract all text from the document
    full_text = "\n".join([para.text for para in doc.paragraphs])
    
    # Verify key elements are present
    assert "Tech Corp" in full_text
    assert "Backend Developer" in full_text
    assert "Developed REST APIs using Python." in full_text
    assert "Python" in full_text
    assert "University of Technology" in full_text